### ISSUE TITLE
Unable to build RPM pkg, failing on missing eslint config file

### ISSUE THREAD

**Issue by martygra** [Open-Xchange-Frontend/generator-ox-ui-module#4]
node version 6.11.1
npm version 3.10.10
yo version 2.0.0
generator-ox-ui-module version 0.16.1
CentOS 7.3

Building a new and empty project, running `grunt rpm-build --include-dependencies` fails with the error:

> Running` "eslint:all" (eslint) task
> Warning: No ESLint configuration found. Use --force to continue.

The entire output can be found here: https://gist.github.com/martygra/c992db678ea1550fcde015a5ada2c8fd

I'm unable to figure out which eslint config file the Grunt task is looking for.

Running `grunt eslint:all` in my project directory successfully completes. 

> [vagrant@localhost mypackage]$ grunt eslint:all
> Running "eslint:all" (eslint) task
> 
> Done, without errors.

Running `grunt eslint:all` in the rpmbuild/BUILD directory, where I believe `exec:rpmbuild` is trying to run it at fails on the missing eslint config:

> [vagrant@localhost mypackage-0.0.0]$ grunt eslint:all
> Running "eslint:all" (eslint) task
> Warning: No ESLint configuration found. Use --force to continue.
> 
> Aborted due to warnings.

**Comment by johnyb** [comment]
Published a new version of open-xchange-shared-grunt-config to npm which contains a fix for this issue. You just need to make sure to upgrade it in your generated package.json.

**Comment by martygra** [comment]
Awesome, thanks. Looks like it's building again.
